export enum EInsurance {
  OSDE = 'OSDE',
  SWISS_MEDICAL = 'Swiss Medical',
  IOMA = 'IOMA',
  PAMI = 'PAMI',
  UNION_PERSONAL = 'Unión Personal',
  OSDEPYM = 'OSDEPYM',
  LUIS_PASTEUR = 'Luis Pasteur',
  JERARQUICOS_SALUD = 'Jerárquicos Salud',
  SANCOR_SALUD = 'Sancor Salud',
  OSECAC = 'OSECAC',
  OSMECON_SALUD = 'OSMECON Salud',
  APROSS = 'Apross',
  OSPRERA = 'OSPRERA',
  OSPAT = 'OSPAT',
  SENACIONAL = 'ASE Nacional',
  OSPIP = 'OSPIP',
}
