export enum EPsychologistSpecialty {
  ANXIETY_DISORDER = 'Trastorno de ansiedad',
  COUPLES_THERAPY = 'Terapia de pareja',
  EATING_DISORDER = 'Trastorno de la alimentación',
  BIPOLAR_DISORDER = 'Trastorno bipolar',
  LIFE_TRANSITIONS = 'Transiciones de vida',
  CHILD_ADOLESCENT_THERAPY = 'Terapia infantil y adolescente',
  SLEEP_DISORDERS = 'Trastornos del sueño',
  DEPRESSION = 'Depresión',
  FAMILY_THERAPY = 'Terapia familiar',
  ADHD = 'TDAH',
  OCD = 'TOC',
  CAREER_COUNSELING = 'Orientación profesional',
  GERIATRIC_PS = 'Psicología geriátrica',
  ANGER_MANAGEMENT = 'Manejo de la ira',
  TRAUMA_PTSD = 'Trauma y TEPT',
  ADDICTION_SUBSTANCE_ABUSE = 'Adicción y abuso de sustancias',
  AUTISM_SPECTRUM_DISORDER = 'Trastorno del espectro autista',
  GRIEF_LOSS = 'Duelo y pérdida',
  LGBTQIA = 'LGBTQIA',
  CHRONIC_PAIN_MANAGEMENT = 'Manejo del dolor crónico',
}
