export enum ETherapyApproach {
  COGNITIVE_BEHAVIORAL_THERAPY = 'Terapia cognitivo-conductual',
  ACCEPTANCE_COMMITMENT_THERAPY = 'Terapia de aceptación y compromiso',
  PSYCHODYNAMIC_THERAPY = 'Terapia psicodinámica',
  FAMILY_SYSTEMS_THERAPY = 'Terapia de sistemas familiares',
  SOLUTION_FOCUSED_BRIEF_THERAPY = 'Terapia breve centrada en soluciones',
  PLAY_THERAPY = 'Terapia de juego',
  DIALECTICAL_BEHAVIORAL_THERAPY = 'Terapia dialéctico-conductual',
  EYE_MOVEMENT_DESENSITIZATION_REPROCESSING = 'Desensibilización y reprocesamiento por movimientos oculares',
  HUMANISTIC_CENTRED_THERAPY = 'Terapia centrada en la persona',
  MINDFULNESS_BASED_THERAPY = 'Terapia basada en la atención plena',
  GESTALT_THERAPY = 'Terapia Gestalt',
  ART_THERAPY = 'Terapia de arte',
  GROUP_THERAPY = 'Terapia de grupo',
}
